var 
  ctx,
  Width, 
  Height,
  coordsX =[],
  coordsY =[],
  Cities = 0,
  Mutations = 0,
  Children = 0,
  StartGA = false,
  NumChromosomes = 50,
  Crossover_kof = 0.8,
  Mutation_kof  = 0.2,
  Matrix,
  bestValue= undefined, 
  BestWay = [],
  BestIndex = 0,
  Iterations = 0,
  chromosomes = [],
  SelfDistance = [];